name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install
      run: sudo apt-get update && sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
    - name: configure
      run: qmake PREFIX=/usr
    - name: make
      run: make
    - name: install
      run: sudo make install
